application: inside-n-out-designs
version: 1
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "1d"

handlers:

- url: /favicon\.ico
  static_files: media/favicon.png
  upload: media/favicon.png
  
- url: /
  static_files: index.html
  upload: index.html
  
- url: /about.html
  static_files: about.html
  upload: about.html
  
- url: /work.html
  static_files: work.html
  upload: work.html

- url: /bootstrap
  static_dir: bootstrap
  expiration: "1d"
  
- url: /media
  static_dir: media
  expiration: "1d"
  
inbound_services:
- warmup

error_handlers:
  - file: default_error.html
