application: inside-n-out-designs
version: 1
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "1d"

handlers:

- url: /robots\.txt
  static_files: robots.txt
  upload: robots.txt

- url: /favicon\.ico
  static_files: media/favicon.png
  upload: media/favicon.png

- url: /static
  static_dir: static
  expiration: "1d"

- url: /bootstrap
  static_dir: bootstrap
  expiration: "1d"
  
- url: /media
  static_dir: media
  expiration: "1d"

- url: /.*
  script: main.app

inbound_services:
- warmup

error_handlers:
  - file: default_error.html
  
pagespeed: 
    enabled_rewriters:
        - InlineImages
